/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author duke
 */
public class Schedule extends javax.swing.JFrame {

    /**
     * Creates new form Schedule
     */
    public Schedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agendaTextView = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        toScheduleButton = new javax.swing.JToggleButton();
        obsTextView = new javax.swing.JLabel();
        obsTextPanel = new javax.swing.JScrollPane();
        obsTextArea = new javax.swing.JTextArea();
        hour = new javax.swing.JLabel();
        hourText = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        dateText = new javax.swing.JTextField();
        price = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();
        service = new javax.swing.JLabel();
        serviceComboBox = new javax.swing.JComboBox<>();
        clientName = new javax.swing.JLabel();
        clientComboBox = new javax.swing.JComboBox<>();
        idClient1 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        schedulePanel = new javax.swing.JLabel();
        scheduleBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agendaTextView.setFont(new java.awt.Font("Notes", 0, 36)); // NOI18N
        agendaTextView.setForeground(new java.awt.Color(255, 255, 255));
        agendaTextView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agendaTextView.setText("Agenda");
        agendaTextView.setToolTipText("");
        agendaTextView.setAlignmentY(0.0F);
        getContentPane().add(agendaTextView, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 50, -1, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Notes", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Juan", "22", "Barba"},
                {"2", "João", "33", null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "cliente", "data", "serviço"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 437, 840, 180));

        toScheduleButton.setFont(new java.awt.Font("Notes", 0, 24)); // NOI18N
        toScheduleButton.setText("Agendar");
        getContentPane().add(toScheduleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 360, 30));

        obsTextView.setFont(new java.awt.Font("Notes", 0, 24)); // NOI18N
        obsTextView.setForeground(new java.awt.Color(255, 255, 255));
        obsTextView.setText("Observações:");
        getContentPane().add(obsTextView, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, -1));

        obsTextArea.setColumns(20);
        obsTextArea.setRows(5);
        obsTextPanel.setViewportView(obsTextArea);

        getContentPane().add(obsTextPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 360, 190));

        hour.setFont(new java.awt.Font("Notes", 0, 24)); // NOI18N
        hour.setForeground(new java.awt.Color(255, 255, 255));
        hour.setText("Hora");
        getContentPane().add(hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        hourText.setFont(new java.awt.Font("Notes", 0, 24)); // NOI18N
        getContentPane().add(hourText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 220, 30));

        date.setFont(new java.awt.Font("Notes", 0, 24)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Data");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        dateText.setFont(new java.awt.Font("Notes", 0, 24)); // NOI18N
        getContentPane().add(dateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 220, 30));

        price.setFont(new java.awt.Font("Notes", 0, 24)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setText("Valor (R$)");
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        priceText.setFont(new java.awt.Font("Notes", 0, 24)); // NOI18N
        getContentPane().add(priceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 220, 30));

        service.setFont(new java.awt.Font("Notes", 0, 24)); // NOI18N
        service.setForeground(new java.awt.Color(255, 255, 255));
        service.setText("Serviço");
        getContentPane().add(service, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        serviceComboBox.setFont(new java.awt.Font("Notes", 0, 24)); // NOI18N
        serviceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(serviceComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 220, 30));

        clientName.setFont(new java.awt.Font("Notes", 0, 24)); // NOI18N
        clientName.setForeground(new java.awt.Color(255, 255, 255));
        clientName.setText("Cliente");
        getContentPane().add(clientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        clientComboBox.setFont(new java.awt.Font("Notes", 0, 24)); // NOI18N
        clientComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alan", "Pedro", "Geovani" }));
        getContentPane().add(clientComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 220, 30));

        idClient1.setFont(new java.awt.Font("Notes", 0, 24)); // NOI18N
        idClient1.setForeground(new java.awt.Color(255, 255, 255));
        idClient1.setText("Id");
        getContentPane().add(idClient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        idText.setFont(new java.awt.Font("Notes", 0, 24)); // NOI18N
        getContentPane().add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 220, 30));

        schedulePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/schedule-panel.png"))); // NOI18N
        getContentPane().add(schedulePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        scheduleBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/schedule.png"))); // NOI18N
        getContentPane().add(scheduleBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Schedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agendaTextView;
    private javax.swing.JComboBox<String> clientComboBox;
    private javax.swing.JLabel clientName;
    private javax.swing.JLabel date;
    private javax.swing.JTextField dateText;
    private javax.swing.JLabel hour;
    private javax.swing.JTextField hourText;
    private javax.swing.JLabel idClient1;
    private javax.swing.JTextField idText;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea obsTextArea;
    private javax.swing.JScrollPane obsTextPanel;
    private javax.swing.JLabel obsTextView;
    private javax.swing.JLabel price;
    private javax.swing.JTextField priceText;
    private javax.swing.JLabel scheduleBackground;
    private javax.swing.JLabel schedulePanel;
    private javax.swing.JLabel service;
    private javax.swing.JComboBox<String> serviceComboBox;
    private javax.swing.JToggleButton toScheduleButton;
    // End of variables declaration//GEN-END:variables
}
